title: Streamdata Gallery AWS Elastic MapReduce
url: aws-elastic-mapreduce.streamdata.gallery
tag: AWS Elastic MapReduce
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: aws-elastic-mapreduce
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
